### PR TITLE
Add menu background

### PR DESCRIPTION
**Pull request by viktorsmari**
@Katearmstrong4 How about this?

Closes issue #5

### CODE REVIEW

**Comment by Katearmstrong4** [comment]
Can we try using the full colour one?

**Comment by viktorsmari** [comment]
What is full color? Less opaque or with a bigger background connecting both icons?

**Comment by Katearmstrong4** [comment]
OK! I see it - can we change the logo for the same one that is in the bottom right-hand corner?
Its green, blue and red.

**Comment by viktorsmari** [comment]
And then remove the white background thing? 
Because then the 'hamburger' menu will still not be seen on a black background.
We can make the menu grey or some other color? Maybe the designer wants a say in this before we make this ugly :laughing:

**Pull request merged**
